### PR TITLE
Added dot to README file

### PR DESCRIPTION
**Pull request by vgaidarji**

### CODE REVIEW

**Comment by vgaidarji** [comment]
@thelvis4 Please review. If you need any explanation - feel free to schedule a 1&1 meeting. Thanks

**Comment by vgaidarji** [comment]
@egor-n @Ilya-Gh guys, welcome to a project. We'll have a 1 hour meeting to discuss the project README file and decide on improvements. Thanks.

**Comment by thelvis4** [comment]
@vgaidarji I think we should have had a meeting before opening this PR.
I believe everybody's opinion is important, even for small changes like this. And we should wait for the common aproval before starting the actual work.
I'm closing this PR because it meet the criteria. You'll open a new PR after we have the common meeting and 1:1 meetings and we are sure we want to have this change.
Thanks!

**Comment by vgaidarji** [comment]
Agree, let's postpone this change until we all agree on some common process.

**Pull request closed without merging**
